language: php

env:
  global:
    - CI_NODE_TOTAL=5

matrix:
  include:
  - php: 5.6
    env:
      - CI_NODE_INDEX=0
  - php: 7.0
    env:
      - CI_NODE_INDEX=1
  - php: 7.1
    env:
      - CI_NODE_INDEX=2
  - php: 7.2
    env:
      - CI_NODE_INDEX=3
  - php: 7.4
    env:
      - REQUIRE_QUALITY_TOOLS=1
      - CI_NODE_INDEX=4

install:
- composer update
- composer install
cache:
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/bin"
before_install:
- |
  set -e ;
  if [[ ! -z "$REINSTALL_TOOLS" ]] ; then
    rm -rf $HOME/bin
  fi

  mkdir -p $HOME/bin

  if [ ! -f $HOME/bin/cc-test-reporter ] ; then
    curl -s -L  \
      https://codeclimate.com/downloads/test-reporter/test-reporter-0.8.0-linux-amd64 \
      -o $HOME/bin/cc-test-reporter
  fi
  chmod +x $HOME/bin/cc-test-reporter
  sha1sum ~/bin/cc-test-reporter
  sha1sum ~/bin/cc-test-reporter  | grep $CC_TEST_REPORTER_SHA1
  echo asdad
- |

  if [[ ! -L $HOME/bin/aws ]] &&  [[ ! -e $HOME/bin/aws   ]]; then
  cat <<EOF > aws-public.key
  -----BEGIN PGP PUBLIC KEY BLOCK-----

  mQINBF2Cr7UBEADJZHcgusOJl7ENSyumXh85z0TRV0xJorM2B/JL0kHOyigQluUG
  ZMLhENaG0bYatdrKP+3H91lvK050pXwnO/R7fB/FSTouki4ciIx5OuLlnJZIxSzx
  PqGl0mkxImLNbGWoi6Lto0LYxqHN2iQtzlwTVmq9733zd3XfcXrZ3+LblHAgEt5G
  TfNxEKJ8soPLyWmwDH6HWCnjZ/aIQRBTIQ05uVeEoYxSh6wOai7ss/KveoSNBbYz
  gbdzoqI2Y8cgH2nbfgp3DSasaLZEdCSsIsK1u05CinE7k2qZ7KgKAUIcT/cR/grk
  C6VwsnDU0OUCideXcQ8WeHutqvgZH1JgKDbznoIzeQHJD238GEu+eKhRHcz8/jeG
  94zkcgJOz3KbZGYMiTh277Fvj9zzvZsbMBCedV1BTg3TqgvdX4bdkhf5cH+7NtWO
  lrFj6UwAsGukBTAOxC0l/dnSmZhJ7Z1KmEWilro/gOrjtOxqRQutlIqG22TaqoPG
  fYVN+en3Zwbt97kcgZDwqbuykNt64oZWc4XKCa3mprEGC3IbJTBFqglXmZ7l9ywG
  EEUJYOlb2XrSuPWml39beWdKM8kzr1OjnlOm6+lpTRCBfo0wa9F8YZRhHPAkwKkX
  XDeOGpWRj4ohOx0d2GWkyV5xyN14p2tQOCdOODmz80yUTgRpPVQUtOEhXQARAQAB
  tCFBV1MgQ0xJIFRlYW0gPGF3cy1jbGlAYW1hem9uLmNvbT6JAlQEEwEIAD4WIQT7
  Xbd/1cEYuAURraimMQrMRnJHXAUCXYKvtQIbAwUJB4TOAAULCQgHAgYVCgkICwIE
  FgIDAQIeAQIXgAAKCRCmMQrMRnJHXJIXEAChLUIkg80uPUkGjE3jejvQSA1aWuAM
  yzy6fdpdlRUz6M6nmsUhOExjVIvibEJpzK5mhuSZ4lb0vJ2ZUPgCv4zs2nBd7BGJ
  MxKiWgBReGvTdqZ0SzyYH4PYCJSE732x/Fw9hfnh1dMTXNcrQXzwOmmFNNegG0Ox
  au+VnpcR5Kz3smiTrIwZbRudo1ijhCYPQ7t5CMp9kjC6bObvy1hSIg2xNbMAN/Do
  ikebAl36uA6Y/Uczjj3GxZW4ZWeFirMidKbtqvUz2y0UFszobjiBSqZZHCreC34B
  hw9bFNpuWC/0SrXgohdsc6vK50pDGdV5kM2qo9tMQ/izsAwTh/d/GzZv8H4lV9eO
  tEis+EpR497PaxKKh9tJf0N6Q1YLRHof5xePZtOIlS3gfvsH5hXA3HJ9yIxb8T0H
  QYmVr3aIUes20i6meI3fuV36VFupwfrTKaL7VXnsrK2fq5cRvyJLNzXucg0WAjPF
  RrAGLzY7nP1xeg1a0aeP+pdsqjqlPJom8OCWc1+6DWbg0jsC74WoesAqgBItODMB
  rsal1y/q+bPzpsnWjzHV8+1/EtZmSc8ZUGSJOPkfC7hObnfkl18h+1QtKTjZme4d
  H17gsBJr+opwJw/Zio2LMjQBOqlm3K1A4zFTh7wBC7He6KPQea1p2XAMgtvATtNe
  YLZATHZKTJyiqA==
  =vYOk
  -----END PGP PUBLIC KEY BLOCK-----
  EOF

    gpg --import aws-public.key

    curl -s -L \
      "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" \
      -o "awscliv2.zip"
    curl -s -L \
        "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip.sig" \
        -o "awscliv2.zip.sig"
    gpg --verify awscliv2.zip.sig  awscliv2.zip
    unzip  awscliv2.zip
    ./aws/install  --bin-dir ~/bin --install-dir ~/bin/aws-cli --update
    rm -rf aws awscliv2.zip awscliv2.zip.sig aws-public.key
    aws --version
  fi

- |
  set -e ;
  if [ "$REQUIRE_QUALITY_TOOLS" != "" ]; then
    composer require --dev --no-update \
      phpstan/phpstan \
      squizlabs/php_codesniffer \
      phpstan/phpstan-phpunit \
      doctrine/coding-standard \
      phpstan/phpstan-symfony \
      phpstan/phpstan-doctrine
  fi

before_script:
  - $HOME/tools/cc-test-reporter before-build
  - mkdir -p coverage

script:
- ./vendor/bin/phpunit --fail-on-warning --coverage-clover ./coverage/coverage.$CI_NODE_INDEX.clover
- "./vendor/bin/behat --colors --strict --stop-on-failure"
- |
  if [ "$REQUIRE_QUALITY_TOOLS" != "" ]; then
    ./vendor/bin/phpcs
    ./vendor/bin/phpstan analyse
  fi
after_script:
  - |
    set -e ;
     if [[ "$TRAVIS_TEST_RESULT" == 0 ]] &&  [[ ! -z "$CC_TEST_REPORTER_ID" ]] ; then
      $HOME/tools/cc-test-reporter format-coverage \
        --input-type clover \
        --output ./coverage/codeclimate.$CI_NODE_INDEX.json \
        ./coverage/coverage.$CI_NODE_INDEX.clover

      aws s3 sync coverage/ "s3://behat-parallel-extension-ci/cc-coverage/$TRAVIS_BUILD_NUMBER"
      aws s3 sync "s3://behat-parallel-extension-ci/cc-coverage/$TRAVIS_BUILD_NUMBER" coverage/

      $HOME/tools/cc-test-reporter sum-coverage \
        --parts $CI_NODE_TOTAL coverage/codeclimate.*.json \
        --output - | \
      $HOME/tools/cc-test-reporter upload-coverage --input -
    fi
