language: php

env:
  global:
    - CI_NODE_TOTAL=5

matrix:
  include:
  - php: 5.6
    env:
      - CI_NODE_INDEX=0
  - php: 7.0
    env:
      - CI_NODE_INDEX=1
  - php: 7.1
    env:
      - CI_NODE_INDEX=2
  - php: 7.2
    env:
      - CI_NODE_INDEX=3
  - php: 7.4
    env:
      - REQUIRE_QUALITY_TOOLS=1
      - CI_NODE_INDEX=4

install:
- composer update
- composer install
cache:
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/tools"
before_install:
- |
  set -e ;
  curl -s https://api.ipify.org
  mkdir -p $HOME/tools
  if [ ! -f $HOME/tools/cc-test-reporter ] ; then
    curl -s -L  \
      https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 \
      -o $HOME/tools/cc-test-reporter
  fi
  chmod +x $HOME/tools/cc-test-reporter
- |
  set -e ;
  if [ "$REQUIRE_QUALITY_TOOLS" != "" ]; then
    composer require --dev --no-update \
      phpstan/phpstan \
      squizlabs/php_codesniffer \
      phpstan/phpstan-phpunit \
      doctrine/coding-standard \
      phpstan/phpstan-symfony \
      phpstan/phpstan-doctrine
  fi

before_script:
  - $HOME/tools/cc-test-reporter before-build
  - mkdir -p coverage

script:
- ./vendor/bin/phpunit --fail-on-warning --coverage-clover ./coverage/coverage.$CI_NODE_INDEX.clover
- "./vendor/bin/behat --colors --strict --stop-on-failure"
- |
  if [ "$REQUIRE_QUALITY_TOOLS" != "" ]; then
    ./vendor/bin/phpcs
    ./vendor/bin/phpstan analyse
  fi
after_script:
  - |
    set -e ;
     if [[ "$TRAVIS_TEST_RESULT" == 0 ]] &&  [[ ! -z "$CC_TEST_REPORTER_ID" ]] ; then
      $HOME/tools/cc-test-reporter format-coverage \
        --input-type clover \
        --output ./coverage/codeclimate.$CI_NODE_INDEX.json \
        ./coverage/coverage.$CI_NODE_INDEX.clover
      $HOME/tools/cc-test-reporter sum-coverage \
        --parts $CI_NODE_TOTAL coverage/codeclimate.*.json \
        --output - | \
      $HOME/tools/cc-test-reporter upload-coverage --input -
    fi
