image:
  - Visual Studio 2019
version: '{build}'
clone_folder: c:\projects\BehatParallelExtension
environment:
  PATH: c:\tools\php;C:\tools\composer;%PATH%
  matrix:
    -
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PHP_VERSION: 7.4
install:
  - ps: |
      Remove-Item --path c:\tools\php -recurse
      function installPhp($version)
      {
        $path = "c:\tools\php\${version}"
        if (Test-Path "$path") {
          return
        }
        appveyor-retry cinst --params ""/InstallDir:${path}""  -y php --version ${version}
        Get-ChildItem -Path "${path}"
        cd ${path}
      }
      installPhp ${PHP_VERSION}

cache:
  - c:\tools\php
  - C:\tools\composer
platform:
  - x86
build_script:
  - ps: ls
test: off
