image:
  - Visual Studio 2019
version: '{build}'
clone_folder: c:\projects\BehatParallelExtension
environment:
  PATH: C:\tools\composer;%PATH%
  matrix:
    -
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PHP_VERSION: 7.4.5
install:
  - $Env:PATH = "c:\tools\php\"+$Env:PHP_VERSION+":"+$Env:PATH
  - echo $Env:PATH
  - ps: |
      #if (Test-Path "c:\tools\php") {
      #  Remove-Item -Path c:\tools\php -Recurse -Force
      #}

      function installPhp($version)
      {
        $path = "c:\tools\php\${version}"
        if (Test-Path "$path") {
          return
        }
        appveyor-retry  choco install php --package-parameters="'/InstallDir:${path}'" --version $version
      }

      function setupPhpIni($version)
      {
        $path = "c:\tools\php\${version}"
        Get-ChildItem -Path "${path}"
        cd ${path}
        copy php.ini-production php.ini
      }

      function installComposer
      {
        if (!(Test-Path C:\tools\composer)) {
          New-Item -path c:\tools -name composer -itemtype directory
        }
        if (!(Test-Path c:\tools\composer\composer.phar)) {
            appveyor-retry appveyor DownloadFile https://getcomposer.org/composer.phar -Filename C:\tools\composer\composer.phar
            Set-Content -path 'C:\tools\composer\composer.bat' -Value ('@php C:\tools\composer\composer.phar %*')
        }
      }

      installPhp $Env:PHP_VERSION
      setupPhpIni $Env:PHP_VERSION
      installComposer

  - cd c:\projects\BehatParallelExtension
  - $Env:PATH = "c:\tools\php\"+$Env:PHP_VERSION+":"+$Env:PATH
  - appveyor-retry composer self-update
  - appveyor-retry composer install --no-progress --ansi
cache:
  - c:\tools\php
  - C:\tools\composer
platform:
  - x86
build_script:
  - ps: ls
test: off
