image:
  - Visual Studio 2019
version: '{build}'
clone_folder: c:\projects\BehatParallelExtension
environment:
  PATH: c:\tools\php;C:\tools\composer;%PATH%
  matrix:
    -
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PHP_VERSION: 7.4
install:
  - sh: |
      rm -rf C:\tools\php

      pwd
      tests/appveyor-php-installer.sh
cache:
  - c:\tools\php
  - C:\tools\composer
platform:
  - x86
build_script:
  - ps: ls
test: off
