version: '{build}'
clone_folder: c:\projects\BehatParallelExtension
environment:
  PATH: c:\tools\php;C:\tools\composer;%PATH%
install:
  - ps: ''
cache:
  - c:\tools\php
  - C:\tools\composer
build_script:
  - ps: ls
test: off
