
services:

  DMarynicz\BehatParallelExtension\Event\EventDispatcherDecorator:
    arguments:
      $eventDispatcher: '@event_dispatcher'

  DMarynicz\BehatParallelExtension\Cli\SigintController:
    autowire: true
    tags:
      - { name: cli.controller, priority: 9999 }

  parallel_extension.php_executable_finder:
    class: Symfony\Component\Process\PhpExecutableFinder
  DMarynicz\BehatParallelExtension\Task\TaskArgumentsBuilder:
    arguments:
      $phpFinder: '@parallel_extension.php_executable_finder'

  DMarynicz\BehatParallelExtension\Util\DetermineNumberOfProcessingUnits: ~
  DMarynicz\BehatParallelExtension\Util\CanDetermineNumberOfProcessingUnits: '@DMarynicz\BehatParallelExtension\Util\DetermineNumberOfProcessingUnits'

  DMarynicz\BehatParallelExtension\Task\ArgumentsBuilder: '@DMarynicz\BehatParallelExtension\Task\TaskArgumentsBuilder'

  DMarynicz\BehatParallelExtension\Task\SpecificationsFinder:
    arguments:
      $suiteRepository: '@suite.registry'
      $specificationFinder: '@specifications.finder'

  DMarynicz\BehatParallelExtension\Task\TestworkSpecificationsFinder: '@DMarynicz\BehatParallelExtension\Task\SpecificationsFinder'

  DMarynicz\BehatParallelExtension\Task\ScenarioTaskFactory:
    autowire: true

  DMarynicz\BehatParallelExtension\Task\FeatureTaskFactory:
    autowire: true

  DMarynicz\BehatParallelExtension\Task\TaskQueue: ~
  DMarynicz\BehatParallelExtension\Task\Queue: '@DMarynicz\BehatParallelExtension\Task\TaskQueue'

  DMarynicz\BehatParallelExtension\Worker\WorkerPoll:
    autowire: true

  DMarynicz\BehatParallelExtension\Worker\Poll: '@DMarynicz\BehatParallelExtension\Worker\WorkerPoll'

  DMarynicz\BehatParallelExtension\Cli\ParallelScenarioController:
    autowire: true
    arguments:
      $decoratedController: '@DMarynicz\BehatParallelExtension\Cli\ParallelScenarioController.inner'
      $taskFactory: '@DMarynicz\BehatParallelExtension\Task\ScenarioTaskFactory'
    decorates: 'cli.controller.exercise'

  DMarynicz\BehatParallelExtension\Cli\ParallelFeatureController:
    autowire: true
    arguments:
      $decoratedController: '@DMarynicz\BehatParallelExtension\Cli\ParallelFeatureController.inner'
      $taskFactory: '@DMarynicz\BehatParallelExtension\Task\FeatureTaskFactory'
    decorates: 'cli.controller.exercise'

  DMarynicz\BehatParallelExtension\Cli\RerunController:
    autowire: true
    arguments:
      $decoratedController: '@DMarynicz\BehatParallelExtension\Cli\RerunController.inner'
    decorates: 'cli.controller.rerun'


  DMarynicz\BehatParallelExtension\Cli\SnippetsController:
    autowire: true
    arguments:
      $decoratedController: '@DMarynicz\BehatParallelExtension\Cli\SnippetsController.inner'
      $registry: '@snippet.registry'
    decorates: 'cli.controller.exercise'

