
services:
  DMarynicz\BehatParallelExtension\Service\EventDispatcherDecorator:
    arguments:
      #EventDispatcherExtension::DISPATCHER_ID
      $eventDispatcher: '@event_dispatcher'

  DMarynicz\BehatParallelExtension\Task\ArgumentsBuilder: ~

  DMarynicz\BehatParallelExtension\Service\Finder\SpecificationsFinder:
    arguments:
      $suiteRepository: '@suite.registry'
      $specificationFinder: '@specifications.finder'

  DMarynicz\BehatParallelExtension\Task\ScenarioTaskFactory:
    autowire: true

  DMarynicz\BehatParallelExtension\Task\Queue: ~

  DMarynicz\BehatParallelExtension\Worker\WorkerPoll:
    autowire: true

  DMarynicz\BehatParallelExtension\Cli\ParallelScenarioController:
    autowire: true
    arguments:
      $decoratedExerciseController: '@DMarynicz\BehatParallelExtension\Cli\ParallelScenarioController.inner'
      $taskFactory: '@DMarynicz\BehatParallelExtension\Task\ScenarioTaskFactory'
    #CliExtension::CONTROLLER_TAG . '.exercise'
    decorates: 'cli.controller.exercise'

  DMarynicz\BehatParallelExtension\Cli\RerunController:
    autowire: true
    arguments:
      $decoratedController: '@DMarynicz\BehatParallelExtension\Cli\RerunController.inner'
      #CliExtension::CONTROLLER_TAG . '.rerun'
    decorates: 'cli.controller.rerun'


  DMarynicz\BehatParallelExtension\Cli\SnippetsController:
    autowire: true
    arguments:
      $decoratedController: '@DMarynicz\BehatParallelExtension\Cli\SnippetsController.inner'
      $registry: '@snippet.registry'
    decorates: 'cli.controller.exercise'

